import { applyEvent, createLiveEvent, fleetSnapshot, trendPoints, WORKING_STATUSES, ATTENTION_STATUSES } from './src/fleet.js';
const $ = (s) => document.querySelector(s);
const colors = { active:'#32b67a', on_mission:'#12b8ca', blocked:'#f17b50', error:'#ef5964', offline:'#707e88', maintenance:'#f6c454', charging:'#8c6bd9', idle:'#95a5ad' };
let events, roster, fleet = new Map(), replayIndex = 0, playing = true, live = false, selected, timer;

async function boot() {
  [events, roster] = await Promise.all([fetch('./events.jsonl').then(r => r.text()).then(t => t.trim().split('\n').map(JSON.parse)), fetch('./robots.json').then(r => r.json())]);
  resetReplay(); bind(); render(); start();
}
function resetReplay() { fleet = new Map(roster.map(r => [r.robot_id, { ...r.start, robot_id:r.robot_id, robot_type:r.robot_type, t:0, status:'idle', battery:100 }])); replayIndex = 0; }
function bind() {
  $('#play').onclick=()=>{playing=!playing; $('#play').textContent=playing?'❚❚ Pause':'▶ Play';};
  $('#mode').onclick=()=>{live=!live; $('#mode').textContent=live?'Restart replay':'Switch to live'; $('#feed-label').textContent=live?'LIVE SIMULATION':'REPLAY FEED'; if(!live) resetReplay(); render();};
  $('#search').oninput=renderRoster; $('#speed').onchange=start;
}
function start(){clearInterval(timer);timer=setInterval(tick, 500 / +$('#speed').value)}
function tick(){if(!playing)return;if(live){fleet=new Map([...fleet].map(([id,e])=>[id,createLiveEvent(e,e.t+5)]));}else {if(replayIndex>=events.length){playing=false;$('#play').textContent='▶ Replay complete';return} const t=events[replayIndex].t; while(replayIndex<events.length&&events[replayIndex].t===t){fleet=applyEvent(fleet,events[replayIndex++]);}}render();}
function render(){const snapshot=fleetSnapshot(fleet); $('#clock').textContent=formatTime(Math.max(...[...fleet.values()].map(e=>e.t))); $('#metrics').innerHTML=[['Fleet online',`${snapshot.total}/8`,'Reporting robots'],['Working',snapshot.working,'Active or on mission'],['Needs attention',snapshot.attention,'Error, blocked, offline, maintenance'],['Average battery',`${snapshot.averageBattery.toFixed(0)}%`,`${snapshot.lowBattery} below 25%`]].map(([l,v,s])=>`<div class="metric"><span>${l}</span><strong>${v}</strong><span>${s}</span></div>`).join(''); renderMap();renderTrend();renderRoster();renderDetail();}
function renderMap(){const map=$('#map');map.querySelectorAll('.robot-dot').forEach(e=>e.remove());for(const e of fleet.values()){const dot=document.createElement('button');dot.className=`robot-dot ${selected===e.robot_id?'selected':''}`;dot.style.cssText=`left:${e.x/2047*100}%;top:${e.y/404*100}%;background:${colors[e.status]}`;dot.title=`${e.robot_id}: ${e.status}`;dot.onclick=()=>{selected=e.robot_id;renderMap();renderRoster();renderDetail()};dot.innerHTML=`<span class="dot-label">${e.robot_id}</span>`;map.append(dot)}}
function renderTrend(){const data=trendPoints(events.slice(0, Math.max(replayIndex,8)));const svg=$('#chart'),w=480,h=150;const path=data.map((p,i)=>`${i?'L':'M'} ${20+i/(Math.max(data.length-1,1))*w} ${170-p.activePercent/100*h}`).join(' ');$('#active-percent').textContent=`${fleetSnapshot(fleet).working/8*100|0}%`;svg.innerHTML=[25,50,75,100].map(v=>`<line class="chart-grid" x1="20" x2="500" y1="${170-v/100*h}" y2="${170-v/100*h}"/><text class="chart-label" x="0" y="${174-v/100*h}">${v}%</text>`).join('')+`<path class="chart-fill" d="${path} L 500 170 L 20 170 Z"/><path class="chart-line" d="${path}"/><text class="chart-label" x="20" y="187">00:00</text><text class="chart-label" x="450" y="187">${formatTime(data.at(-1)?.t||0)}</text>`}
function renderRoster(){const q=$('#search').value.toLowerCase();const robots=[...fleet.values()].filter(e=>e.robot_id.includes(q)||e.status.includes(q)).sort((a,b)=>(ATTENTION_STATUSES.has(b.status)-ATTENTION_STATUSES.has(a.status))||a.robot_id.localeCompare(b.robot_id));$('#robot-list').innerHTML=robots.map(e=>`<div class="robot-row ${selected===e.robot_id?'selected':''}" data-id="${e.robot_id}"><i class="status-dot" style="background:${colors[e.status]}"></i><div><b>${e.robot_id.toUpperCase()}</b> <small>${e.robot_type}</small></div><span class="badge">${e.status.replace('_',' ')}</span><span>${e.battery.toFixed(0)}%</span></div>`).join('');document.querySelectorAll('.robot-row').forEach(row=>row.onclick=()=>{selected=row.dataset.id;renderMap();renderRoster();renderDetail()})}
function renderDetail(){const box=$('#detail'),e=fleet.get(selected);if(!e){box.innerHTML='<p class="eyebrow">SELECT A ROBOT</p><h2>Robot detail</h2><p class="muted">Select a marker or roster row to inspect its latest telemetry.</p>';return}box.innerHTML=`<p class="eyebrow">LATEST TELEMETRY · ${formatTime(e.t)}</p><h2>${e.robot_id.toUpperCase()} <small>${e.robot_type}</small></h2><span class="status" style="background:${colors[e.status]}">${e.status.replace('_',' ').toUpperCase()}</span><div class="detail-grid"><div><span>Battery</span><strong>${e.battery.toFixed(1)}%</strong></div><div><span>Position</span><strong>${e.x.toFixed(0)}, ${e.y.toFixed(0)}</strong></div><div><span>Assignment</span><strong>${WORKING_STATUSES.has(e.status)?'In progress':'No active task'}</strong></div><div><span>Operator action</span><strong>${ATTENTION_STATUSES.has(e.status)?'Review now':'None needed'}</strong></div></div>`}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};boot();
